# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actionneurs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x63tionneurs.proto\x12\x04\x65nac\"\xd8\x04\n\nSmartServo\x12\n\n\x02id\x18\x01 \x01(\r\x12-\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\x1c.enac.SmartServo.CommandType\x12(\n\x04type\x18\x03 \x01(\x0e\x32\x1a.enac.SmartServo.ServoType\x12\r\n\x05newID\x18\x04 \x01(\r\x12\x10\n\x08position\x18\x05 \x01(\r\x12\x11\n\treg_write\x18\x06 \x01(\x08\x12\x16\n\x0e\x65ndless_status\x18\x07 \x01(\x08\x12\x0e\n\x06torque\x18\x08 \x01(\r\x12\x15\n\renable_torque\x18\t \x01(\x08\x12\x11\n\tmin_angle\x18\n \x01(\r\x12\x11\n\tmax_angle\x18\x0b \x01(\r\x12\x35\n\tdirection\x18\x0c \x01(\x0e\x32\".enac.SmartServo.RotationDirection\x12\r\n\x05speed\x18\r \x01(\r\"\xab\x01\n\x0b\x43ommandType\x12\n\n\x06SET_ID\x10\x00\x12\x08\n\x04PING\x10\x01\x12\x10\n\x0cSET_BAUDRATE\x10\x02\x12\x08\n\x04MOVE\x10\x03\x12\x0c\n\x08READ_POS\x10\x04\x12\x0e\n\nMOVE_SPEED\x10\x05\x12\x0f\n\x0bSET_ENDLESS\x10\x06\x12\x08\n\x04TURN\x10\x07\x12\x0e\n\nSET_TORQUE\x10\x08\x12\x11\n\rTORQUE_ENABLE\x10\t\x12\x0e\n\nSET_LIMITS\x10\n\"\x1e\n\tServoType\x12\x07\n\x03STS\x10\x00\x12\x08\n\x04\x41X12\x10\x01\"8\n\x11RotationDirection\x12\x14\n\x10\x43ounterclockwise\x10\x00\x12\r\n\tClockwise\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actionneurs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SMARTSERVO._serialized_start=28
  _SMARTSERVO._serialized_end=628
  _SMARTSERVO_COMMANDTYPE._serialized_start=367
  _SMARTSERVO_COMMANDTYPE._serialized_end=538
  _SMARTSERVO_SERVOTYPE._serialized_start=540
  _SMARTSERVO_SERVOTYPE._serialized_end=570
  _SMARTSERVO_ROTATIONDIRECTION._serialized_start=572
  _SMARTSERVO_ROTATIONDIRECTION._serialized_end=628
# @@protoc_insertion_point(module_scope)
